resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/jjovah/flight-school
    branch: master
- name: statging-app
  type: cf
  source:
      api: https://api.run.pivotal.io
      username: jjovah
      password: jjovahSDC4$
      organization: Devonfield
      space: development

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/build.yml
  - put: statging-app
      params:
        manifest: flight-school/mainifest.yml
